version: '3'

services:
  btb_grafana_dashboard:
    image: grafana/grafana:latest
    container_name: btb_grafana_dashboard
    restart: always
    env_file:
      - .env
    ports:
      - ${GRAFANA_HTTP_PORT}:${GRAFANA_HTTP_PORT}
    volumes:
      - ./grafana/dashboard.json:/app/dashboard.json
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_HTTP_PORT=${GRAFANA_HTTP_PORT}
