version: '3'

services:
  btb_grafana:
    image: grafana/grafana:latest
    container_name: btb_grafana
    restart: always
    ports:
      - 42069:42069
    volumes:
      - ./example_database.db:/app/crypto_trading.db
      - ./dashboard.json:/app/dashboard.json
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
    environment:
      - GF_SERVER_HTTP_PORT=42069
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=cVZRYPP2ogLs
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:42069/api/health',
        ]
      interval: 1m
      timeout: 1s
      retries: 3
